const GAME_DATA = {
  spells: {
    // --- Original 7 spells ---
    fire:      { name: 'ファイア',       mpCost: 4,  damage: [18, 28],   type: 'magic', element: 'fire',   learnLevel: 1  },
    blaze:     { name: 'ブレイズ',       mpCost: 9,  damage: [42, 62],   type: 'magic', element: 'fire',   learnLevel: 7  },
    inferno:   { name: 'インフェルノ',   mpCost: 18, damage: [80, 120],  type: 'magic', element: 'fire',   learnLevel: 14 },
    thunder:   { name: 'サンダー',       mpCost: 13, damage: [48, 72],   type: 'magic', element: 'thunder',learnLevel: 11 },
    heal:      { name: 'ヒール',         mpCost: 5,  heal:   [30, 45],   type: 'heal',  learnLevel: 1  },
    healmore:  { name: 'ヒールモア',     mpCost: 11, heal:   [75, 110],  type: 'heal',  learnLevel: 8  },
    barrier:   { name: 'バリア',         mpCost: 6,  buffStat:'def', buffAmount:12, buffTurns:3, type:'buff', learnLevel: 5 },
    // --- 10 New spells ---
    ice:       { name: 'アイス',         mpCost: 7,  damage: [25, 38],   type: 'magic', element: 'ice',    learnLevel: 3  },
    blizzard:  { name: 'ブリザード',     mpCost: 16, damage: [65, 95],   type: 'magic', element: 'ice',    learnLevel: 12 },
    storm:     { name: 'ストーム',       mpCost: 10, damage: [40, 60],   type: 'magic', element: 'wind',   learnLevel: 9  },
    quake:     { name: 'クエイク',       mpCost: 14, damage: [55, 82],   type: 'magic', element: 'earth',  learnLevel: 13 },
    light:     { name: 'ライト',         mpCost: 15, damage: [60, 90],   type: 'magic', element: 'holy',   learnLevel: 15 },
    shadow:    { name: 'シャドウ',       mpCost: 12, damage: [50, 75],   type: 'magic', element: 'dark',   learnLevel: 10 },
    healall:   { name: 'ヒールオール',   mpCost: 22, heal:   [60, 90],   type: 'healall', learnLevel: 16 },
    revive:    { name: 'リバイブ',       mpCost: 28,                      type: 'revive',  learnLevel: 17 },
    force:     { name: 'フォース',       mpCost: 25, damage: [105, 155], type: 'magic', element: 'arcane', learnLevel: 18 },
    magicwall: { name: 'マジックウォール', mpCost: 9, buffStat:'def', buffAmount:20, buffTurns:4, type:'buff', learnLevel: 6 },
  },

  spellLevelUp: [
    { level: 1,  spells: ['fire', 'heal'] },
    { level: 3,  spells: ['ice'] },
    { level: 5,  spells: ['barrier'] },
    { level: 6,  spells: ['magicwall'] },
    { level: 7,  spells: ['blaze'] },
    { level: 8,  spells: ['healmore'] },
    { level: 9,  spells: ['storm'] },
    { level: 10, spells: ['shadow'] },
    { level: 11, spells: ['thunder'] },
    { level: 12, spells: ['blizzard'] },
    { level: 13, spells: ['quake'] },
    { level: 14, spells: ['inferno'] },
    { level: 15, spells: ['light'] },
    { level: 16, spells: ['healall'] },
    { level: 17, spells: ['revive'] },
    { level: 18, spells: ['force'] },
  ],

  items: {
    potion:    { name: 'ポーション',     type: 'heal',    healAmount: 35,  price: 30,  desc: 'HPを35回復する。' },
    hiPotion:  { name: 'ハイポーション', type: 'heal',    healAmount: 100, price: 80,  desc: 'HPを100回復する。' },
    elixir:    { name: 'エリクサー',     type: 'healFull',                 price: 300, desc: 'HPを全回復する。' },
    ether:     { name: 'エーテル',       type: 'healMP',  healAmount: 25,  price: 50,  desc: 'MPを25回復する。' },
    antidote:  { name: '解毒薬',         type: 'cure',    cureStatus:'poison', price: 20, desc: '毒を治す。' },
    fullEther: { name: 'フルエーテル',   type: 'healMP',  healAmount: 60,  price: 120, desc: 'MPを60回復する。' },
  },

  weapons: {
    bronzeSword: { name: '青銅の剣',   atk: 8,  price: 150, desc: '攻撃力+8。',  where:'shop' },
    ironSword:   { name: '鉄の剣',     atk: 18, price: 0,   desc: '攻撃力+18。', where:'cave' },
    legendBlade: { name: '伝説の剣',   atk: 35, price: 0,   desc: '攻撃力+35。', where:'castle' },
  },

  armors: {
    leatherArmor: { name: '革の鎧',       def: 6,  price: 100, desc: '防御力+6。',  where:'shop' },
    chainMail:    { name: 'チェインメイル', def: 14, price: 0,   desc: '防御力+14。', where:'cave' },
    dragonMail:   { name: 'ドラゴンメイル', def: 28, price: 0,   desc: '防御力+28。', where:'castle' },
  },

  // Party member base stats (deep-copied into game.partyData on init)
  partyMembers: {
    erina: {
      name: 'エリナ', role: '魔法使い',
      hp: 42, maxHp: 42, mp: 38, maxMp: 38,
      atk: 9, def: 6, spd: 13,
      spells: ['fire', 'ice', 'thunder', 'heal'],
      sprite: 'erina', alive: true,
    },
    gard: {
      name: 'ガルド', role: '戦士',
      hp: 75, maxHp: 75, mp: 8, maxMp: 8,
      atk: 22, def: 18, spd: 7,
      spells: [],
      sprite: 'gard', alive: true,
    },
    luna: {
      name: 'ルナ', role: '聖職者',
      hp: 58, maxHp: 58, mp: 50, maxMp: 50,
      atk: 8, def: 11, spd: 10,
      spells: ['heal', 'healmore', 'healall', 'barrier', 'revive'],
      sprite: 'luna', alive: true,
    },
  },

  monsters: {
    slime:      { name:'スライム',    hp:18,  atk:7,  def:3,  spd:8,  exp:12,  gold:6,   emoji:'🟢', color:'#4CAF50', sprite:'slime',      actions:['attack','attack','attack'] },
    goblin:     { name:'ゴブリン',    hp:28,  atk:11, def:6,  spd:10, exp:22,  gold:10,  emoji:'👺', color:'#8BC34A', sprite:'goblin',      actions:['attack','attack','attack'] },
    wyvern:     { name:'ワイバーン',  hp:42,  atk:16, def:8,  spd:14, exp:38,  gold:18,  emoji:'🐉', color:'#FF9800', sprite:'wyvern',      actions:['attack','attack','breath'] },
    forestTroll:{ name:'フォレストトロール', hp:180, atk:26, def:13, spd:8, exp:200, gold:80, emoji:'👹', color:'#33691E', sprite:'forestTroll', isBoss:true, actions:['attack','attack','smash','regen'] },

    skeleton:  { name:'スケルトン',   hp:52,  atk:20, def:14, spd:9,  exp:52,  gold:26,  emoji:'💀', color:'#ECEFF1', sprite:'skeleton',    actions:['attack','attack','attack'] },
    caveBat:   { name:'ケイブバット', hp:38,  atk:16, def:10, spd:18, exp:42,  gold:20,  emoji:'🦇', color:'#7C4DFF', sprite:'caveBat',     actions:['attack','attack','poison'] },
    darkMage:  { name:'ダークメイジ', hp:58,  atk:26, def:12, spd:13, exp:68,  gold:36,  emoji:'🧙', color:'#3F51B5', sprite:'darkMage',    actions:['attack','magic','magic'] },
    caveDragon:{ name:'ケイブドラゴン', hp:420, atk:44, def:24, spd:12, exp:550, gold:200, emoji:'🐲', color:'#D32F2F', sprite:'caveDragon',  isBoss:true, actions:['attack','breath','breath','tailSwipe'], phase2Trigger:210 },

    darkKnight:{ name:'ダークナイト', hp:96,  atk:44, def:28, spd:15, exp:125, gold:62,  emoji:'⚔️', color:'#455A64', sprite:'darkKnight',  actions:['attack','attack','charge'] },
    demon:     { name:'デーモン',     hp:112, atk:50, def:22, spd:16, exp:150, gold:72,  emoji:'😈', color:'#880E4F', sprite:'demon',       actions:['attack','magic','roar'] },
    archDemon: { name:'アーチデーモン',hp:135, atk:56, def:26, spd:18, exp:175, gold:88,  emoji:'👿', color:'#B71C1C', sprite:'archDemon',   actions:['attack','magic','magic','drain'] },
    demonKing: { name:'魔王ゾルディアーク', hp:1100, atk:82, def:44, spd:20, exp:9999, gold:9999, emoji:'👑', color:'#1a0020', sprite:'demonKing', isBoss:true, actions:['attack','attack','darkBlast','darkBlast','drain','rage'], phase2Trigger:550 },
  },

  areas: {
    village: {
      name:'エルフィア村', type:'town', emoji:'🏘️', music:'town',
      desc:'平和な村。旅の出発点。', locked:false,
      shopItems:   ['potion','hiPotion','ether','antidote','fullEther'],
      shopWeapons: ['bronzeSword'],
      shopArmors:  ['leatherArmor'],
    },
    forest: {
      name:'翠の森', type:'dungeon', emoji:'🌲', music:'field',
      desc:'緑豊かな森。魔物が出没する。', locked:false,
      monsters:['slime','goblin','wyvern'], boss:'forestTroll', rooms:5,
      bossDefeated:false, encounterRate:0.35,
      treasures:[{item:'potion',count:2,room:2,found:false},{item:'ether',count:1,room:4,found:false}],
    },
    cave: {
      name:'黒岩の洞窟', type:'dungeon', emoji:'⛰️', music:'field',
      desc:'暗く険しい洞窟。強敵が待つ。', locked:true,
      monsters:['skeleton','caveBat','darkMage'], boss:'caveDragon', rooms:6,
      bossDefeated:false, encounterRate:0.40,
      treasures:[{weaponId:'ironSword',room:2,found:false},{armorId:'chainMail',room:4,found:false},{item:'hiPotion',count:2,room:5,found:false}],
    },
    castle: {
      name:'魔王城', type:'dungeon', emoji:'🏰', music:'field',
      desc:'魔王の城。最後の決戦の地。', locked:true,
      monsters:['darkKnight','demon','archDemon'], boss:'demonKing', rooms:8,
      bossDefeated:false, encounterRate:0.45,
      treasures:[{weaponId:'legendBlade',room:3,found:false},{armorId:'dragonMail',room:6,found:false},{item:'elixir',count:1,room:7,found:false}],
    },
  },

  story: {
    intro: [
      { speaker:'ナレーター', text:'遠い昔、世界は「光のクリスタル」の加護によって守られていた。その輝きは生命を育み、人々に希望をもたらし続けた。' },
      { speaker:'ナレーター', text:'しかし今から七日前の夜、空が震え、大地が揺れた。魔王ゾルディアークが深淵より蘇り、光のクリスタルを奪い去ったのだ。' },
      { speaker:'ナレーター', text:'クリスタルを失った世界には、じわじわと闇が満ちていく。植物は枯れ、空は曇り、魔物の数が日に日に増していった。' },
      { speaker:'長老カルタス', text:'目を覚ましたか、若者よ。ようやく眠りから覚めたか。心配したぞ。' },
      { speaker:'長老カルタス', text:'お前が倒れていたのは三日前のことじゃ。魔王の放った闇の波動に飲み込まれ、気を失っておった。' },
      { speaker:'長老カルタス', text:'しかしな、お前の中に眠る「光の血」がその闇を跳ね返した証拠でもある。お前こそが選ばれし勇者なのじゃ。' },
      { speaker:'長老カルタス', text:'魔王が光のクリスタルを奪い去った今、世界中で異変が起きている。このままでは完全に闇に沈む。残された時間は少ない。' },
      { speaker:'長老カルタス', text:'北の翠の森を抜け、黒岩の洞窟を越えれば魔王城に着く。道は険しく、強大な魔物が行く手を阻むだろう。' },
      { speaker:'長老カルタス', text:'しかし恐れることはない。お前は一人ではない。旅の途中で必ず力になってくれる者が現れるはずだ。' },
      { speaker:'長老カルタス', text:'まずは村の店で装備を整えてから旅立つがよい。そして…わしの孫娘エリナが、どうしても同行したいと言っておる。話してやってくれ。' },
      { speaker:'エリナ', text:'勇者さん、やっと起きた！心配してたんだから。私、一緒に行く！魔法の修行をずっと積んできたの。絶対に役に立てる！' },
      { speaker:'エリナ', text:'おじい様には危険だって止められたけど…クリスタルが失われたまま毎日魔物が増えていく。黙って村に居るなんてできない！' },
      { speaker:'勇者', text:'…危険だぞ。本当に来るのか？' },
      { speaker:'エリナ', text:'当たり前！私の炎と氷の魔法、頼りにしてね。あと、おじい様みたいに心配性にならないで。私、強いから！' },
      { speaker:'長老カルタス', text:'エリナ、気をつけるのじゃぞ。勇者よ、孫娘を頼んだ。二人で力を合わせ、必ずクリスタルを取り戻してくれ。健闘を祈る！' },
    ],
    forestBoss: [
      { speaker:'ナレーター', text:'翠の森の最奥。古木が空を覆い、木漏れ日さえ届かぬ薄暗い場所に大地が揺れた。木々がへし折れ、巨大な影が現れた！' },
      { speaker:'エリナ', text:'あれが…フォレストトロール！魔王に支配された森の守護者だわ。気をつけて！' },
      { speaker:'フォレストトロール', text:'ガアアアァ！この森に踏み込む人間がいるとは！貴様ら、命知らずな奴らめ！' },
      { speaker:'勇者', text:'退け！俺たちは魔王城へ向かう。道を開けてもらう！' },
      { speaker:'フォレストトロール', text:'ダメだダメだ！魔王様の命令じゃ。ここを通りたくば、この儂を倒してみせろ！' },
      { speaker:'エリナ', text:'大きいけど怖くない！私の魔法で焼き払ってやる！' },
      { speaker:'フォレストトロール', text:'うぬ、人間風情が！かかってこい！この儂を倒せるというか！' },
      { speaker:'ナレーター', text:'決戦が始まった。大地が震え、木々がざわめく中、勇者とエリナはトロールに立ち向かった！' },
    ],
    forestClear: [
      { speaker:'ナレーター', text:'フォレストトロールが轟音とともに倒れた！長く支配されていた森に、やわらかな光が戻り始めた。' },
      { speaker:'エリナ', text:'やった…！やっつけた！でも…あそこに誰かいる。木陰に。' },
      { speaker:'ガルド', text:'…強い奴らだ。俺はガルド。流れ者の戦士だ。魔物に囲まれて一人で戦ってたが、もう限界だった。' },
      { speaker:'ガルド', text:'お前らの戦いを見ていた。本物の力だ。俺でよければ、一緒に連れていってくれないか。剣の腕だけは自信がある。' },
      { speaker:'勇者', text:'もちろんだ。一緒に来てくれ、ガルド。力を貸してくれ。' },
      { speaker:'ガルド', text:'…承知した。魔王を倒すまで、この剣、貴様らのために使おう。絶対に守ってみせる。' },
    ],
    caveBoss: [
      { speaker:'ナレーター', text:'黒岩の洞窟の最深部。地の底から唸り声が響き、岩壁が振動する。巨大な龍の影が炎のたいまつに照らされた！' },
      { speaker:'エリナ', text:'この声…ケイブドラゴン！洞窟の主よ。魔王の力で狂暴化してる。気をつけて！' },
      { speaker:'ガルド', text:'でかいな…。だが退くわけにはいかない！' },
      { speaker:'ケイブドラゴン', text:'グルルル…。人間よ、貴様らが魔王様を倒しに来た勇者一行か。しぶとい連中だ。' },
      { speaker:'ケイブドラゴン', text:'ここを通したら魔王様に顔向けできぬ。このドラゴンの牙と炎を受けてみよ！ここで朽ち果てろ！' },
      { speaker:'勇者', text:'行くぞ、みんな！力を合わせれば必ず勝てる！' },
      { speaker:'エリナ', text:'ブリザードで冷やしてやる！ガルド、正面を頼む！' },
      { speaker:'ガルド', text:'わかった！俺が引きつける。遠慮なく魔法をぶち込め！' },
    ],
    caveClear: [
      { speaker:'ナレーター', text:'ケイブドラゴンが崩れ落ちた。洞窟の奥から淡い光が漏れている。魔王城が近い。' },
      { speaker:'ガルド', text:'やったな。このドラゴンも魔王に操られていたのか…。本来は違う姿だったのかもしれん。' },
      { speaker:'エリナ', text:'待って、あそこ…！格子のある牢屋みたいなところに、誰かいる！' },
      { speaker:'ルナ', text:'…助けて。私はルナ。光の神殿の聖職者です。ケイブドラゴンに捕まってずっとここに閉じ込められていました。' },
      { speaker:'勇者', text:'ルナさん、大丈夫か。もう安全だ。一緒に来てくれ。' },
      { speaker:'ルナ', text:'ありがとうございます。あなたたちが勇者様ですね。光が、あなたたちの周りに輝いて見えます。私の回復魔法が力になれるはず。一緒に連れていってください。' },
    ],
    castleEnter: [
      { speaker:'ナレーター', text:'魔王城の巨大な門が、何かに引き寄せられるように開いた。中から禍々しい闇の気配が波のように押し寄せてくる。' },
      { speaker:'エリナ', text:'この空気…！鳥肌が立つ。クリスタルの光が完全に封じ込められているのが感じ取れる。' },
      { speaker:'ガルド', text:'引き返すつもりはない。ここまで来て逃げるくらいなら死んだほうがマシだ。行くぞ！' },
      { speaker:'ルナ', text:'皆さん、神の加護を。光の力がまだここに残っています。それが私たちを導いてくれる。' },
      { speaker:'謎の声', text:'よくここまで来た、人間どもよ。だが、ここが貴様らの墓場だ…。フハハハハ！' },
      { speaker:'勇者', text:'声がする…。これが魔王の声か。負けるつもりはない。行こう、みんな！' },
    ],
    finalBoss: [
      { speaker:'ナレーター', text:'玉座の間。漆黒のオーラを纏った魔王ゾルディアークが、巨大な玉座からゆっくりと立ち上がった。その圧倒的な威圧感に空気が震える。' },
      { speaker:'魔王ゾルディアーク', text:'フハハハ！ここまで辿り着くとは…村人の子どもと、寄せ集めの仲間よ。その根性だけは認めよう。' },
      { speaker:'ガルド', text:'でかい口を叩くな魔王。クリスタルを返せ！' },
      { speaker:'魔王ゾルディアーク', text:'返す？フン、笑わせるな。世界はもともと闇のものだ。光の時代など、まやかしに過ぎぬ。' },
      { speaker:'エリナ', text:'違う！光があるから、人も植物も、全ての命が輝けるんだ！あなたには分からないの！？' },
      { speaker:'魔王ゾルディアーク', text:'分からなくて結構。力こそが真実、闇こそが世界の本質だ！弱者の慰めに光は要らぬ！' },
      { speaker:'ルナ', text:'神よ、どうか力をお与えください…。私たちに、この戦いを勝ち抜く力を…！' },
      { speaker:'勇者', text:'魔王！お前が何を言おうと、クリスタルは取り戻す。これが俺たち全員の答えだ！' },
      { speaker:'魔王ゾルディアーク', text:'言うではないか、勇者よ。ならば力で証明してみせよ！貴様らを地の底に叩き落とす！覚悟しろ！' },
      { speaker:'ナレーター', text:'決戦の時が来た。四人の戦士が、世界の命運を賭けて闇の王に立ち向かう！' },
    ],
    finalBossPhase2: [
      { speaker:'魔王ゾルディアーク', text:'ぐうっ！この儂がここまで追い詰められるとは…よかろう！真の力を解放してやろう！' },
      { speaker:'ナレーター', text:'魔王が変貌した！漆黒のオーラが爆発的に膨れ上がり、城全体が激しく揺れた！' },
      { speaker:'エリナ', text:'圧力が…！ものすごいオーラ…。負けないで、みんな！' },
      { speaker:'ガルド', text:'まだ終わってないぞ！来い、魔王！この剣で必ず終わらせる！' },
      { speaker:'魔王ゾルディアーク', text:'愚かな人間どもよ！これが真の魔王の力だ！闇の底に永遠に沈め！！' },
    ],
    ending: [
      { speaker:'ナレーター', text:'魔王ゾルディアークが断末魔の叫びとともに崩れ落ちた。光のクリスタルが玉座の奥から現れ、眩い輝きを放った。' },
      { speaker:'エリナ', text:'クリスタル…！輝いてる！本当に取り戻した！信じられない…！' },
      { speaker:'ルナ', text:'光よ…光の神よ。クリスタルが戻ってきた…！感謝します！ありがとうございます！' },
      { speaker:'ガルド', text:'…終わった。本当に終わったんだな。よくやった、勇者。お前がいなければこんな日は来なかった。' },
      { speaker:'勇者', text:'みんながいたから勝てたんだ。一人じゃ絶対に無理だった。本当にありがとう。' },
      { speaker:'ナレーター', text:'しかし、城が崩れ始めた！四人はクリスタルを守りながら、崩落する魔王城から命がけで脱出した。' },
      { speaker:'ナレーター', text:'城を出ると、空が清らかに晴れ渡っていた。七日ぶりに、太陽が世界を照らした。' },
      { speaker:'エリナ', text:'見て！太陽が…！空が青い…！クリスタルが力を取り戻している！' },
      { speaker:'ルナ', text:'光の神殿へ急ぎましょう。クリスタルが戻る場所はあそこです。' },
      { speaker:'ナレーター', text:'四人は光の神殿へとクリスタルを還した。台座に置かれた瞬間、眩い光が世界全土へと広がった。' },
      { speaker:'ナレーター', text:'枯れた植物が芽吹き、濁った川が清らかになり、空の雲が晴れていった。世界に平和が戻った。' },
      { speaker:'ガルド', text:'…俺は旅を続けるつもりだ。だがもし次に魔物が現れたとき、また共に戦おう。待ってるぜ。' },
      { speaker:'エリナ', text:'私もっと修行するわ！いつかもっとすごい魔法使いになる。また会おうね！絶対に！' },
      { speaker:'ルナ', text:'神の加護がいつも皆さんとともにありますように。この戦いを私は生涯忘れません。' },
      { speaker:'ナレーター', text:'こうして勇者と仲間たちの名は永く語り継がれた。光のクリスタルの輝きが続く限り、世界に闇は訪れないだろう。' },
    ],
  },
};
